"""init

<<<<<<<< HEAD:backend/migrations/versions/5e02d5bce64c_init.py
Revision ID: 5e02d5bce64c
Revises: 
Create Date: 2025-08-06 00:22:54.542182

"""
========
Revision ID: 94654c06787d
Revises: 
Create Date: 2025-08-05 21:27:54.224395

"""
import sqlalchemy as sa
>>>>>>>> e659b97b42d18aeed6ef6bc01bb7f7cf733fc71a:backend/migrations/versions/94654c06787d_init.py
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<<< HEAD:backend/migrations/versions/5e02d5bce64c_init.py
revision = '5e02d5bce64c'
========
revision = '94654c06787d'
>>>>>>>> e659b97b42d18aeed6ef6bc01bb7f7cf733fc71a:backend/migrations/versions/94654c06787d_init.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workout_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_type_id', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_session')
    op.drop_table('goal')
    op.drop_table('user')
    op.drop_table('exercise_type')
    # ### end Alembic commands ###
